version: "3.7"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - default

  db:
    image: mysql:8.0.26
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
